name: Logs Firebase → Discord

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install firebase-admin node-fetch@2

      - run: node index.js
